
import { useState } from "react";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardFooter, CardHeader, CardTitle } from "@/components/ui/card";
import { Download, Loader2, FileText, CheckCircle } from "lucide-react";
import { toast } from "sonner";

interface DocumentPreviewProps {
  documentUrl: string | null;
  documentType: string;
  isLoading: boolean;
}

const DocumentPreview = ({ documentUrl, documentType, isLoading }: DocumentPreviewProps) => {
  const [isDownloading, setIsDownloading] = useState(false);
  
  const handleDownload = async () => {
    if (!documentUrl) return;
    
    try {
      setIsDownloading(true);
      
      // In a real implementation, this would download the document
      // For demonstration, we'll simulate a download delay
      await new Promise(resolve => setTimeout(resolve, 1500));
      
      // For demonstration, create a mock download action
      // In production, this would be a real download action
      const a = document.createElement('a');
      a.href = documentUrl;
      a.download = `${documentType === 'cv' ? 'CV' : 'Cover-Letter'}-${Date.now()}.pdf`;
      document.body.appendChild(a);
      a.click();
      document.body.removeChild(a);
      
      toast.success("Document downloaded successfully");
    } catch (error) {
      console.error("Error downloading document:", error);
      toast.error("Failed to download document");
    } finally {
      setIsDownloading(false);
    }
  };
  
  return (
    <Card className="h-full">
      <CardHeader>
        <CardTitle>Document Preview</CardTitle>
      </CardHeader>
      
      <CardContent className="flex-1">
        {isLoading ? (
          <div className="h-[500px] flex items-center justify-center border rounded-md bg-muted/30">
            <div className="text-center">
              <Loader2 className="h-8 w-8 animate-spin mx-auto mb-4" />
              <p>Generating your document...</p>
              <p className="text-sm text-muted-foreground mt-2">
                This may take a few moments
              </p>
            </div>
          </div>
        ) : documentUrl ? (
          <div className="h-[500px] border rounded-md bg-white overflow-hidden">
            <div className="h-full flex flex-col items-center justify-center p-8 text-center">
              <CheckCircle className="h-16 w-16 text-primary mb-4" />
              <h3 className="text-xl font-medium mb-2">Document Generated!</h3>
              <p className="text-muted-foreground mb-6">
                Your {documentType === 'cv' ? 'CV' : 'Cover Letter'} is ready for download.
              </p>
              
              <div className="flex justify-center">
                <Button
                  onClick={handleDownload}
                  disabled={isDownloading}
                  className="gap-2"
                >
                  {isDownloading ? (
                    <>
                      <Loader2 className="h-4 w-4 animate-spin" />
                      Downloading...
                    </>
                  ) : (
                    <>
                      <Download className="h-4 w-4" />
                      Download {documentType === 'cv' ? 'CV' : 'Cover Letter'}
                    </>
                  )}
                </Button>
              </div>
              
              <div className="mt-8 bg-muted/30 p-4 rounded-md w-full max-w-md">
                <h4 className="font-medium mb-2">Disclaimer</h4>
                <p className="text-sm text-muted-foreground">
                  This document was generated by AI based on the information you provided. 
                  Please review and personalize it further before submitting to employers.
                </p>
              </div>
            </div>
          </div>
        ) : (
          <div className="h-[500px] flex items-center justify-center border rounded-md bg-muted/30">
            <div className="text-center px-8">
              <FileText className="h-12 w-12 mx-auto mb-4 text-muted-foreground" />
              <h3 className="text-lg font-medium mb-2">No Document Generated Yet</h3>
              <p className="text-muted-foreground">
                Fill in the required information and click "Generate" to create your 
                {documentType === 'cv' ? ' CV' : ' Cover Letter'}.
              </p>
            </div>
          </div>
        )}
      </CardContent>
      
      <CardFooter className="border-t p-4">
        <p className="text-sm text-muted-foreground">
          AI-generated documents are meant to be a starting point. Always review and customize
          them to match your personal style and the specific job requirements.
        </p>
      </CardFooter>
    </Card>
  );
};

export default DocumentPreview;
