// @deno-types="https://raw.githubusercontent.com/denoland/deno/main/cli/dts/lib.deno.ns.d.ts"
// @ts-ignore
import { serve } from "https://deno.land/std@0.177.0/http/server.ts";
// @ts-ignore
import { HfInference } from "https://esm.sh/@huggingface/inference@2.3.2";
// @ts-ignore
import { createClient } from "https://esm.sh/@supabase/supabase-js@2.39.3";

const corsHeaders = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Headers': 'authorization, x-client-info, apikey, content-type',
};

serve(async (req: Request) => {
  if (req.method === 'OPTIONS') {
    return new Response(null, { headers: corsHeaders });
  }
  
  try {
    const supabaseUrl = Deno.env.get('SUPABASE_URL')!;
    const supabaseKey = Deno.env.get('SUPABASE_ANON_KEY')!;
    const supabase = createClient(supabaseUrl, supabaseKey, {
        global: { headers: { Authorization: req.headers.get('Authorization')! } },
    });

    // Verify User
    const { data: { user }, error: authError } = await supabase.auth.getUser();
    if (authError || !user) {
        return new Response(JSON.stringify({ error: 'Unauthorized' }), { status: 401, headers: corsHeaders });
    }

    const { 
      documentType, 
      language, 
      templateId, 
      jobTitle, 
      experience, 
      skills, 
      jobDescription 
    } = await req.json();
    
    // Validate inputs
    if (!documentType || !jobTitle) {
      return new Response(JSON.stringify({ error: 'Missing required fields' }), { status: 400, headers: corsHeaders });
    }

    // Initialize Hugging Face
    const hfKey = Deno.env.get('HUGGING_FACE_ACCESS_TOKEN');
    if (!hfKey) {
        return new Response(JSON.stringify({ error: 'AI Service Config Missing' }), { status: 500, headers: corsHeaders });
    }
    const hf = new HfInference(hfKey);

    const systemPrompt = `You are an expert ${language === 'es' ? 'redactor de CVs' : 'resume writer'}. 
    Create a professional ${documentType === 'cv' ? 'Resume Summary and Experience improvement' : 'Cover Letter'} for a ${jobTitle}.
    Skills: ${skills}. Experience: ${experience}.`;

    const userPrompt = `Draft a professional summary and 3 bullet points for my experience. Job Description target: ${jobDescription || 'General'}`;

    // Generate Content
    const tg = await hf.textGeneration({
      model: 'TinyLlama/TinyLlama-1.1B-Chat-v1.0', // Fast, cheap model
      inputs: `${systemPrompt}\nUser: ${userPrompt}\nAssistant:`,
      parameters: {
        max_new_tokens: 400,
        temperature: 0.7,
        do_sample: true,
      }
    });

    const generatedText = Array.isArray(tg) ? tg[0]?.generated_text : (tg as any)?.generated_text;
    
    // Structure the response to match the expected format
    const content = {
        documentType,
        language,
        timestamp: new Date().toISOString(),
        sections: {
            header: {
                title: jobTitle,
                subtitle: "Generated by SupplyChainKE AI"
            },
            summary: generatedText || "Could not generate content.",
            skills: skills.split(',').map((s: string) => s.trim())
        }
    };

    // Store in DB
    const { data, error: dbError } = await supabase
      .from('generated_documents')
      .insert({
        user_id: user.id,
        document_type: documentType,
        language,
        template_id: templateId,
        content: content, // Storing full JSON
        expiration_date: new Date(Date.now() + 86400000).toISOString(), // 24h
      })
      .select('id')
      .single();

      if (dbError) {
          console.error("DB Error:", dbError);
          // We return success with content even if DB save fails, but log it.
      }

    return new Response(JSON.stringify({ 
        success: true,
        documentId: data?.id,
        content 
    }), { headers: { ...corsHeaders, 'Content-Type': 'application/json' } });

  } catch (error) {
    console.error('Error:', error);
    return new Response(JSON.stringify({ error: String(error) }), { status: 500, headers: { ...corsHeaders, 'Content-Type': 'application/json' } });
  }
});
