
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import { Database } from '@/types/database.types';

const supabaseUrl = import.meta.env.VITE_SUPABASE_URL || 'https://dqlfolsngrspnlpzzthv.supabase.co';
const supabaseAnonKey = import.meta.env.VITE_SUPABASE_ANON_KEY || 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRxbGZvbHNuZ3JzcG5scHp6dGh2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzc3ODM0NzksImV4cCI6MjA1MzM1OTQ3OX0.DZEChMYZRL0HrV65n6ewVDSiFiFh9TudG61mcoHQW8k';

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

// Add console warning if env vars aren't set
if (!import.meta.env.VITE_SUPABASE_URL || !import.meta.env.VITE_SUPABASE_ANON_KEY) {
  console.warn('Supabase URL or Anonymous Key not found in environment variables. Using fallback values.');
}

export const supabase = createClient<Database>(supabaseUrl, supabaseAnonKey);
