// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dqlfolsngrspnlpzzthv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRxbGZvbHNuZ3JzcG5scHp6dGh2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzc3ODM0NzksImV4cCI6MjA1MzM1OTQ3OX0.DZEChMYZRL0HrV65n6ewVDSiFiFh9TudG61mcoHQW8k";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);